### ISSUE TITLE
Merge followed by CellML export generates CellML models that are invalid in SemGen and OpenCOR

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#127] opened 2015-10-27 16:14 UTC
Performing the PHN merge works OK but attempting to load the resulting CellML models back into SemGen fails. I believe this has something to do with an error associated with the way that SG prunes models following a merge. I think the pruning is removing some submodels, but not in a complete way. Maybe CellML-type connections between variables in pruned submodels are still making their way into the exported CellML code?

**Comment by thompsct** [comment] 2015-10-27 16:30
Is there any associated console information?

**Comment by thompsct** [comment] 2015-10-27 19:44
Loading it in OpenCOR fails as well.

**Comment by thompsct** [comment] 2015-10-27 20:51
Looks like the internal interfaces are not being written correctly for the first model (which serves as the merged base).

**Comment by maxneal** [comment] 2015-10-28 02:08
I think part of the problem may be the way that FunctionalSubmodels get copied when we clone model 1 for the merging operation. Maybe the relationshipSubmodelMap isn't being copied correctly? I think the copied version may refer to FunctionalSubmodels that are not actually in the cloned model (i.e. they refer to ones that are in the original model).

**Comment by maxneal** [comment] 2015-10-28 02:15
Also, Chris can you give me an example of the duplicate connections and namespace conflict errors that you found when doing the Hinch round trip?  When I do it on my end the SG-generated version works OK in OpenCOR. What tool are you using to identify those issues, BTW?

**Comment by maxneal** [comment] 2015-10-28 15:00
I believe I've smushed the main bug here. The relationshipSubmodelMap wasn't being copied correctly during model cloning. Now when I do the PHN merge, both the PH and PHN cellml files load successfully in SG and in OpenCOR. Bug fix is in the MacBundle branch. Planning to merge with master today.

**Comment by thompsct** [comment] 2015-10-28 15:39
Great! The round trip CellML file does load correctly in OpenCOR. 

As an aside, we may want to convert CellML 1.0 files to CellML 1.1 files to avoid potential conflicts in the future.

**Comment by thompsct** [comment] 2015-10-28 18:05
I can confirm this error is fixed.

**Closed by thompsct** 2015-10-28 18:05 UTC
Labels: bug, SG 3.0
