### ISSUE TITLE
Browser not loading in non-Windows platforms

### ISSUE THREAD

**Issue by rcjames1004** [thompsct/SemGen#24] opened 2015-01-29 07:21 UTC
We need to use the swt.jar specific to the platform we're on. Unfortunately, the swt.jar for Mac has compatibility issues with the java browser we're using. Apparently there are workarounds. Let's use this bug to investigate those workarounds and implement the best solution.

**Comment by rcjames1004** [comment] 2015-01-29 18:30
Potential solution: http://netbeans.dzone.com/how-to-nb-djnative-swing

**Comment by rcjames1004** [comment] 2015-04-02 08:00
After a ton of trying and failing I found the bug that explains this issue in detail: https://bugs.eclipse.org/bugs/show_bug.cgi?id=418245. Basically, Java 7 and SWT have compatibility issues that cause SemGen to crash when we try and load the browser. Unfortunately, this means that the stage will not load in SemGen until this bug is fixed, and it doesn't look like it will be fixed anytime soon. (it was open on 9-2013) :/.

**Comment by thompsct** [comment] 2015-04-02 12:34
Would upgrading the project to Java 8 possibly fix the problem? I've switched over to 8 in a local branch and it didn't flag any code issues. Something to look into after the conference.

**Comment by rcjames1004** [comment] 2015-04-03 04:31
According to the bug, no. I tried it a while ago with no luck. I assume they'd update the bug if they fixed it, but who knows. I can give it another go after the demo.

**Comment by rcjames1004** [comment] 2015-05-08 09:16
The stage is fully functioning on my windows machine. Can someone sync to the JxBrowser branch and test it out on a Mac plz?

**Comment by GrahamKim** [comment] 2015-05-08 17:35
Works on my Mac! Thanks for the fix Ryan.
It'd probably be good to mute all the red log messages on the console, if there is a way to do so.

**Comment by maxneal** [comment] 2015-05-08 18:20
Yep works on mine, too. And I agree with Graham that it would be nice to mute the red console messages.

**Comment by rcjames1004** [comment] 2015-05-08 19:04
Great! Thanks for trying this out so quickly.

Yea, those red messages suck. I'll see what I can do. Once I get a long term license from the JxBrowser team I'll work on integrating these changes into master, then close this bug

**Comment by rcjames1004** [comment] 2015-05-21 04:23
The long term license is checked in and functioning (on my machine)! Please give it a try on your own machine. Better yet, Max, would you mind creating a build from this branch that we can all test out? At this point the main thing we should be verifying is that the browser loads without issue, but if you'd like to test stage functionality after the browser loads be my guest :).

One more thing, Max. The JxBrowser team would like us to note that JxBrowser is proprietary software. From their team: "We would also greatly appreciate if you make a note on your website that JxBrowser is proprietary software." Something to consider.

**Comment by maxneal** [comment] 2015-05-21 16:13
When I run the JxBrowser branch from within Eclipse everything seems to work OK but when I create a build the stage does not show up.

I looked at the JxBrowser log messages and it appears that the error is due to reading stage.html from within the jar file versus from the file system.

Here's the line near the end of the JxBrowser log messages from my build that indicates the error:

11:45:30 INFO: READ:  OnDidFailProvisionalLoadMessage{type=OnDidFailProvisionalLoad, uid=11, frameId=1, isMainFrame=true, validatedURL='jar:file:/Users/max_neal/_UW/SemGenGrant/SGbuilds/privateBuilds/21May2015_JxBrowser/SemGen.jar!/resources/stage.html?testMode=false', errorCode=-3, errorDescription='Unknown error.'}, SocketInfo{channelId=0, browserId=0, channelType=Browser}


I noted that when run from Eclipse, the "validatedURL" value for the corresponding event message points to an actual file in my file system, not within a jar: 'file:///Users/max_neal/Documents/workspaceLUNA/SemGen_JxBrowser/bin/resources/stage.html?testMode=false'

So could this be fixed by using getResourceAsStream() to read in stage.html rather than getResource()?
See http://stackoverflow.com/questions/20389255/java-reading-a-resource-file-from-within-jar

M

**Comment by rcjames1004** [comment] 2015-05-21 20:24
The old framework had a nice api for loading local, packaged files, I'm not sure if JxBrowser has the same. I'm looking into the stackoverlow post and other potential options. Thanks for finding this. (I probably should have built a release myself before sending my post. I'll do that this time).

**Comment by rcjames1004** [comment] 2015-05-27 18:19
Looks like JxBrowser doesn't support loading files from a jar. To get around this issue we'll need to copy the files to a temp directory and load the stage from that new directory. This is all detailed in the following forum post: https://groups.google.com/a/teamdev.com/forum/#!searchin/jxbrowser-forum/resource$20file/jxbrowser-forum/bK7KFB33E1o/qzmwQfulDUQJ

**Comment by rcjames1004** [comment] 2015-05-27 19:12
This issue should be resolved in check in eec2e73deef29eb1f733796368b99f67dc49862e. Please verify. Unfortunately, I wasn't able to successfully build SemGen.jar and try this myself, so I'm only assuming the issue is fixed. Max, would you mind creating a build? Also, are you doing anything special when you export SemGen from eclipse?

**Comment by maxneal** [comment] 2015-05-27 21:05
I pulled in the changes to the JxBrowser branch on my machine but the stage isn't working correctly when I run from within Eclipse, nor when I create a build. In both cases when I attempt to load a stage tab I get a big ol' "This webpage is not available" error message on the stage. Not exactly sure what the problem is. Here's the log output from the console, up until it starts spitting out javascript:

Loading SemGen...Loaded.
05:00:12 INFO: OS name: Mac OS X
05:00:12 INFO: JRE version: 1.8.0_45-b14 32-bit
05:00:12 INFO: JxBrowser version: 5.2
05:00:12 INFO: Starting IPC...
05:00:12 INFO: Starting IPC Server...
05:00:12 INFO: Starting IPC Process...
05:00:12 INFO: Start Chromium process...
05:00:12 INFO: Command line: /var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/MacOS/jxbrowser 1101 74062 
05:00:12 INFO: [0527/170012:INFO:main-delegate.cpp(48)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:12 INFO: [0527/170012:INFO:main-delegate.cpp(48)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:12 INFO: [0527/170012:INFO:main-delegate.cpp(48)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:12 INFO: [0527/170012:INFO:main-delegate.cpp(48)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:12 INFO: READ:  OnHelloMessage{type=OnHelloMessage, uid=1, message='cid:0,type:Main'}, null
05:00:12 INFO: Channel is accepted: SocketChannel{cid=0, bid=-1, type=Main}
05:00:12 INFO: IPC is started.
05:00:12 INFO: WRITE: CreateBrowserMessage{type=CreateBrowser, uid=0, channelId=0, contextId=-1, cacheDir='/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/data/Cache', memoryDir='/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/data/Memory', dataDir='/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/data', currentLocale='en-us', proxyType=-1, proxyRules='null', proxyBypassRules='null', proxyAutoConfigURL='null', defaultZoomLevel=0.0}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
05:00:12 INFO: [0527/170012:INFO:main-delegate.cpp(56)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:12 INFO: [0527/170012:INFO:main-delegate.cpp(56)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:12 INFO: READ:  OnHelloMessage{type=OnHelloMessage, uid=2, message='cid:0,bid:0,type:Browser'}, null
05:00:12 INFO: Channel is accepted: SocketChannel{cid=0, bid=0, type=Browser}
05:00:12 INFO: Channel is connected: SocketChannel{cid=0, bid=0, type=Browser}
05:00:12 INFO: WRITE: SetNetworkDelegateConfigMessage{type=SetNetworkDelegateConfig, uid=1, browserContextId=-1, disableMessages=true}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
05:00:12 INFO: WRITE: LoadURLMessage{type=LoadURL, uid=2, url='about:blank', frameId=-1, extraHeaders='null', postData=null}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:12 INFO: [0527/170012:INFO:main-delegate.cpp(56)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:12 INFO: [0527/170012:INFO:main-delegate.cpp(56)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:12 INFO: READ:  com.teamdev.jxbrowser.chromium.internal.ipc.message.OnRenderViewCreatedMessage@a0305fd, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: [0527/170012:INFO:main-delegate.cpp(56)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:13 INFO: [0527/170013:INFO:main-delegate.cpp(56)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:13 INFO: [0527/170013:INFO:main-delegate.cpp(56)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:13 INFO: [0527/170013:INFO:main-delegate.cpp(56)] Frameworks path: /private/var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/jxbrowser-chromium-39.0.2171.52.5.2/jxbrowser.app/Contents/Frameworks
05:00:13 INFO: [0527/170013:ERROR:renderer_main.cc(207)] Running without renderer sandbox
05:00:13 INFO: READ:  OnHelloMessage{type=OnHelloMessage, uid=1, message='cid:0,bid:0,type:Render'}, null
05:00:13 INFO: Channel is accepted: SocketChannel{cid=0, bid=0, type=Render}
05:00:13 INFO: Channel is connected: SocketChannel{cid=0, bid=0, type=Render}
05:00:13 INFO: READ:  OnHandleLoadMessage{type=OnHandleLoadMessage, uid=2, url='about:blank', loadType=5, loadPpolicy=2, isBackForward=false, isRedirect=false, cancel=false}, SocketInfo{channelId=0, browserId=0, channelType=Render}
05:00:13 INFO: WRITE: OnHandleLoadMessage{type=OnHandleLoadMessage, uid=2, url='about:blank', loadType=5, loadPpolicy=2, isBackForward=false, isRedirect=false, cancel=false}, SocketInfo{channelId=0, browserId=0, channelType=Render}
05:00:13 INFO: READ:  OnDidStartProvisionalLoadForFrameMessage{type=OnDidStartProvisionalLoadForFrame, uid=4, frameId=1, parentFrameId=-1, isMainFrame=true, validatedURL='about:blank', isErrorPage=false}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnDidCommitProvisionalLoadForFrameMessage{type=OnDidCommitProvisionalLoadForFrame, uid=5, frameId=1, isMainFrame=true, transitionType=1, url='about:blank'}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnStatusChangeMessage{type=OnStatusChangeMessage, uid=6, url=''}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnDocumentLoadedInFrameMessage{type=OnDocumentLoadedInFrame, uid=7, frameId=1, isMainFrame=true}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnDidFinishLoadMessage{type=OnDidFinishLoad, uid=8, frameId=1, isMainFrame=true, validatedURL='about:blank'}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
Loading SemGen web browser
SemGen web browser loaded
05:00:13 INFO: WRITE: LoadURLMessage{type=LoadURL, uid=3, url='java.io.BufferedInputStream@7cc7c92f?testMode=false', frameId=-1, extraHeaders='null', postData=null}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: WRITE: ScreenChangedMessage{type=ScreenChanged, uid=4, screenId=69675264}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnHandleLoadMessage{type=OnHandleLoadMessage, uid=3, url='http://java.io.BufferedInputStream@7cc7c92f/?testMode=false', loadType=5, loadPpolicy=2, isBackForward=false, isRedirect=false, cancel=false}, SocketInfo{channelId=0, browserId=0, channelType=Render}
05:00:13 INFO: WRITE: OnHandleLoadMessage{type=OnHandleLoadMessage, uid=3, url='http://java.io.BufferedInputStream@7cc7c92f/?testMode=false', loadType=5, loadPpolicy=2, isBackForward=false, isRedirect=false, cancel=false}, SocketInfo{channelId=0, browserId=0, channelType=Render}
05:00:13 INFO: READ:  OnShouldBeginRequestMessage{type=OnShouldBeginRequest, uid=9, browserContextId=-1, url='http://java.io.BufferedInputStream@7cc7c92f/?testMode=false', method='GET', resourceType=0, cancel=false}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
05:00:13 INFO: WRITE: OnShouldBeginRequestMessage{type=OnShouldBeginRequest, uid=9, browserContextId=-1, url='http://java.io.BufferedInputStream@7cc7c92f/?testMode=false', method='GET', resourceType=0, cancel=false}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
05:00:13 INFO: READ:  OnDidStartProvisionalLoadForFrameMessage{type=OnDidStartProvisionalLoadForFrame, uid=10, frameId=1, parentFrameId=-1, isMainFrame=true, validatedURL='http://java.io.BufferedInputStream@7cc7c92f/?testMode=false', isErrorPage=false}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnCanGetCookiesMessage{type=OnCanGetCookies, uid=11, url='http://java.io.BufferedInputStream@7cc7c92f/?testMode=false', cookies='', browserContextId=-1, canGetCookies=true}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
05:00:13 INFO: WRITE: OnCanGetCookiesMessage{type=OnCanGetCookies, uid=11, url='http://java.io.BufferedInputStream@7cc7c92f/?testMode=false', cookies='', browserContextId=-1, canGetCookies=true}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
05:00:13 INFO: READ:  OnDidFailProvisionalLoadMessage{type=OnDidFailProvisionalLoad, uid=13, frameId=1, isMainFrame=true, validatedURL='http://java.io.BufferedInputStream@7cc7c92f/?testMode=false', errorCode=-105, errorDescription='Unable to resolve the server's DNS address.'}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnDidStartProvisionalLoadForFrameMessage{type=OnDidStartProvisionalLoadForFrame, uid=14, frameId=1, parentFrameId=-1, isMainFrame=true, validatedURL='data:text/html,chromewebdata', isErrorPage=true}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnDidCommitProvisionalLoadForFrameMessage{type=OnDidCommitProvisionalLoadForFrame, uid=15, frameId=1, isMainFrame=true, transitionType=1, url='http://java.io.BufferedInputStream@7cc7c92f/?testMode=false'}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnStatusChangeMessage{type=OnStatusChangeMessage, uid=16, url=''}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnDocumentAvailableInMainFrameMessage{type=OnDocumentAvailableInMainFrame, uid=17}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnDidCreateScriptContextMessage{type=OnDidCreateScriptContext, uid=4, frameId=-1, contextPtr=140692531911184}, SocketInfo{channelId=0, browserId=0, channelType=Render}
05:00:13 INFO: WRITE: OnDidCreateScriptContextMessage{type=OnDidCreateScriptContext, uid=4, frameId=-1, contextPtr=140692531911184}, SocketInfo{channelId=0, browserId=0, channelType=Render}
05:00:13 INFO: READ:  OnGetJSFunctionsMessage{type=OnGetJSFunctions, uid=5, functionNames=''}, SocketInfo{channelId=0, browserId=0, channelType=Render}
05:00:13 INFO: WRITE: OnGetJSFunctionsMessage{type=OnGetJSFunctions, uid=5, functionNames='sendJavaCommand '}, SocketInfo{channelId=0, browserId=0, channelType=Render}
05:00:13 INFO: READ:  OnTitleChangeMessage{type=OnTitleChange, uid=18, title='http://java.io.BufferedInputStream@7cc7c92f/?testMode=false is not available'}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: [0527/170013:INFO:CONSOLE(3183)] "i18n-values: Missing value for "primaryParagraph"", source: data:text/html,chromewebdata (3183)
05:00:13 INFO: READ:  OnConsoleMessage{type=OnConsoleMessage, uid=19, level=1, message='i18n-values: Missing value for "primaryParagraph"', lineNumber=3183, sourceId='data:text/html,chromewebdata'}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnDocumentLoadedInFrameMessage{type=OnDocumentLoadedInFrame, uid=20, frameId=1, isMainFrame=true}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: READ:  OnDidFinishLoadMessage{type=OnDidFinishLoad, uid=21, frameId=1, isMainFrame=true, validatedURL='data:text/html,chromewebdata'}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
05:00:13 INFO: WRITE: ExecuteJavaScriptMessage{type=ExecuteJavaScript, uid=7, frameId=-1, javaScript='var head = document.getElementsByTagName('head')[0];

**Comment by rcjames1004** [comment] 2015-05-28 04:16
I added a few more logs in dfdfb560c49c7740d5b03271c8cfea1833747748. Can you give this another try and post the logs that you find? I'm particularly interested in the new log lines starting with "Browser files copied sucessfully to " and "Loading the stage @: ". They should help us figure out what's going on.

Also, what OS are you using? I would be surprised if this failed on Windows (although I'm surprised this is failing at all, especially since the browser loaded successfully according to the logs you posted).

**Comment by maxneal** [comment] 2015-05-29 20:42
Hi Ryan,

Here's the output that I get with your new changes:

Loading SemGen web browser
Browser files copied sucessfully to /var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/SemGen-5016901370667373632075435646798537
Loading the stage @: /var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/SemGen-5016901370667373632075435646798537/resources/stage.html?testMode=false
SemGen web browser loaded

But I still just get the "This webpage is not available" screen when the stage appears.

When I click on the "Details" link, it says:

"The server at **var** can't be found, because the DNS lookup failed. DNS is the network service that translates a website's name to its Internet address. This error is most often caused by having no connection to the Internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing Chromium from accessing the network."

**Comment by maxneal** [comment] 2015-05-29 20:49
On the off chance that I knew what I was doing, I prepended the 'stageDir' string variable with "file://" and the stage now loads successfully. Should I push that change?

**Comment by maxneal** [comment] 2015-05-29 22:18
Unfortunately my edit did not fix the problem after building SG and running outside Eclipse. I get hopefully log messages...

Browser files copied sucessfully to /var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/SemGen-5042352376742178433201461388644799
Loading the stage @: file:///var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/SemGen-5042352376742178433201461388644799/resources/stage.html?testMode=false

...but get a "This webpage not found error" on stage load. The details provided are:

No webpage was found for the web address: file:///var/folders/qw/01gv_w0d6t54l0g_p6mmmghr0000gn/T/SemGen-5042352376742178433201461388644799/resources/stage.html?testMode=false

**Comment by rcjames1004** [comment] 2015-05-30 00:46
Thanks Max, I think you've identified the problem--JxBrowswer can't find the file because of how the url is constructed. My guess is because there's an unintended "/" between the file protocol (i.e. file://) and the file directory (i.e. /var/...). When the two are put together there are three "/"s instead of two (i.e. file:/// instead of file://). I can think of two ways to test this theory:

First, remove the extra "/":
1) Start SemGen
2) Load the stage (and get file not found)
3) Copy the file location from the logs (i.e. copy file:///var/...)
4) Remove the extra "/" between "file:" and "var" so there are only two
5) Paste the modified file location in any browser address bar

Second, forget the file protocol:
1) Start SemGen
2) Load the stage (and get file not found)
3) Copy the file location WITHOUT the protocol from the logs (i.e. copy /var/...)
4) Paste the file location in any browser address bar

If the browser loads the stage successfully in either of the scenarios above then we've identified the issue. If you have time to test these out please do. If not, I should be able to get my hands on a mac and test them myself early next week.

**Comment by rcjames1004** [comment] 2015-05-30 02:02
So, it just occurred to me that Macs and Linux machines are both built on Unix and I have a Linux VM, so I can probably catch a lot of Mac issues, like this one. I fired up SemGen on my Linux VM and I'm seeing the same issue. It doesnt appear to be what I thought it was above. On my Linux machine the "?" character after stage.html is getting url encoded, which throws off the path look up. JxBrowser thinks the path is "...stage.html%3FtestMode=false" instead of "...stage.html?testMode=false". I added the test mode flag there so the stage is standalone, which makes it easier to test JavvaScript (you don't have to load SemGen and can just debug in the browser).

Anyways, I think I have a fix. No need to test anything yet (ignore my last message). I'll post another comment after I check in.

**Comment by rcjames1004** [comment] 2015-05-30 10:34
I missed your last two comments when I initially replied, I would have saved a bunch of time had I seen them :/. I checked in a fix for the fille:// protocol issue. Now we just need to figure out what's going on when running SemGen outside of eclipse :/. I'll have to think about this one, or try it out myself.

It would help if I could build a jar successfully, but when I try and export SemGen to a runnable jar using eclipse I get errors. Max, are you doing anything special when you build a release?

**Comment by maxneal** [comment] 2015-05-30 20:01
I don't think I'm doing anything special when I build from Eclipse. I just highlight the project on the left, then go to File > Export. Then I select runnable jar, and save it out. What are the errors you're getting?

**Comment by maxneal** [comment] 2015-07-15 22:05
Ryan decided to just store the external stage files in the 'cfg' folder rather than try to copy them to a temp folder from within the jar file. This appears to be a working solution.

We can now run the stage on Mac from within Eclipse and from a standalone build. 

Closing this sucker.

**Closed by maxneal** 2015-07-15 22:05 UTC
Labels: bug, high priority, SG 3.0

**Comment by rcjames1004** [comment] 2015-07-15 22:44
Whoop! Whoop!
